version: "3.8"
services:
    postgres:
        image: postgres
        container_name: pg-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: "test"
            POSTGRES_USER: "test"
        healthcheck:
           test: [ "CMD-SHELL", "pg_isready -U test" ]
           interval: 10s
           timeout: 5s
           retries: 5
        ports:
           - "5436:5432" 
        volumes:
           - postgres-data:/var/lib/postgresql/data
    webapi:
        image: example-api2
        container_name: api
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - 8085:8080
        env_file:
            - .env
volumes:
    postgres-data: